### PR TITLE
S3C-3571 create Gradle project,CI setup,Add Jacoco,Pmd,Spotbugs

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**

### CODE REVIEW

**Review by tcarmet — APPROVED** [review]

**Comment by terrydervaux** [comment]
Is it possible to have the coverage percentage reported in the CI logs stdio?

**Comment by terrydervaux** [comment]
Is it possible to have the coverage report uploaded in our homemade Artifactory(I need to find the right name for that)? e.g: docs-ring-s3c CI → https://github.com/scality/docs-ring-s3c/blob/841e0cf57446f0fa4f8d5c99441eb087e9c8735f/eve/main.yml#L7

**Review by NicolasT — COMMENTED** [review]
Would've been good if this were split in multiple commits: one to set up the Gradle project, one to set up PMD, one to integrate with Eve,... (or those in some different order).

Also, is APL2 the right license for this project? How was this decided?

**Comment by saitharunthodupunuru** [comment]
> Is it possible to have the coverage report uploaded in our homemade Artifactory(I need to find the right name for that)? e.g: docs-ring-s3c CI → https://github.com/scality/docs-ring-s3c/blob/841e0cf57446f0fa4f8d5c99441eb087e9c8735f/eve/main.yml#L7

Added a new commit to add the report files. I will see if I can simplify more to understand which of these files are code coverage and which are lint reports

**Comment by saitharunthodupunuru** [comment]
> Would've been good if this were split in multiple commits: one to set up the Gradle project, one to set up PMD, one to integrate with Eve,... (or those in some different order).
> 
> Also, is APL2 the right license for this project? How was this decided?

Nicolas,
We decided on making this project as open source. I just used APL2 license as many open source projects scality had same license. Please suggest otherwise

**Comment by saitharunthodupunuru** [comment]
> Is it possible to have the coverage report uploaded in our homemade Artifactory(I need to find the right name for that)? e.g: docs-ring-s3c CI → https://github.com/scality/docs-ring-s3c/blob/841e0cf57446f0fa4f8d5c99441eb087e9c8735f/eve/main.yml#L7

I added a commit for uploading the coverage reports and lint analysis reports and printing same on logs.

**Review by terrydervaux — APPROVED** [review]
LGTM, thanks for the reports 👍

**Review by tmacro — APPROVED** [review]

**Pull request merged**
