### PR TITLE
Feature/S3C-3737 bootstrap vmware osis sample stub

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**
Merging original OSIS-Sample-Stub provided by vmware:
https://github.com/vmware-samples/object-storage-extension-samples/tree/master/vmware-ose-osis-stub.

This PR is only for merging sample stub for osis from Vmware to our project. API implementation follows in other tickets.

### CODE REVIEW

**Comment by saitharunthodupunuru** [comment]
This PR is only for merging sample stub for osis from Vmware to our project. API implementation follows in other tickets.

**Review by anurag4DSB — APPROVED** [review]
Approving blindly as this this code has been taken from OSIS-Sample-Stub provided by vmware

**Review by naren-scality — APPROVED** [review]

**Comment by NicolasT** [comment]
Can you add the exact revision of the upstream repository from which this code was taken, for tracking purposes, in the related commit message?

**Comment by saitharunthodupunuru** [comment]
> Can you add the exact revision of the upstream repository from which this code was taken, for tracking purposes, in the related commit message?

Updated commit message as suggested. Please let me know if anything else missing

**Pull request merged**
